# Generated by Django 3.2.6 on 2022-09-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
