# Generated by Django 3.2.6 on 2022-09-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
    ]
