# Generated by Django 3.2.6 on 2022-10-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0007_auto_20221010_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivaldate',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
