# Generated by Django 3.2.6 on 2022-10-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0008_alter_arrivaldate_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_id',
        ),
    ]
