# Generated by Django 3.2.6 on 2022-10-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0009_remove_orders_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
