# Generated by Django 3.2.6 on 2022-10-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0010_orders_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_id',
        ),
    ]
